import Head from 'next/head'
import Image from 'next/image'
import MemberCard from '../components/about/MemberCard'
import TestimonialCard from '../components/testimonials/TestimonialCard'
import NewCard from '../components/news/NewCard'
import Link from 'next/link'
import { BsArrowRight } from 'react-icons/bs'

export default function Home({ members, testimonials, news }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='w-full max-w-6xl my-8 sm:mx-4'>
        <div className='flex flex-wrap px-2 mb-6'>
          <div className='w-full grid grid-cols-2 md:grid-cols-4 gap-4'>
            <div className='col-span-2 md:h-96 flex flex-col justify-center'>
              <h2 className='text-3xl font-bold'>Hola Bienvenidxs</h2>
              <p className='sm:pr-8'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam sit et molestias
                consectetur perferendis voluptates corporis. Impedit soluta porro corporis accusamus
                ullam dolorum, illo quod eveniet, nulla unde ex aliquam. Molestiae, possimus velit
                aliquam voluptas officiis excepturi ullam expedita? Quo magni incidunt fugiat nisi
                sed vero, iusto blanditiis praesentium. Veritatis itaque unde minus nesciunt
                distinctio illum commodi soluta rem eius eligendi. Vero voluptas, ipsam sunt sed eos
                maiores odio dolore accusamus fugit officia porro, omnis quisquam! Non debitis dicta
                soluta.
              </p>
              <div className='flex items-center py-4'>
                <button
                  className='shadow bg-red-600 hover:bg-red-500 focus:shadow-outline focus:outline-none text-white text-lg font-medium py-3 px-5 rounded-2xl'
                  type='submit'
                >
                  Contactanos
                </button>
              </div>
            </div>
            <div
              className='col-span-2 h-96 md:h-96 rounded-3xl bg-center'
              style={{
                background: `url(${'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80'})`,
                backgroundSize: 'cover',
                backgroundRepeat: 'no-repeat',
                backgroundPosition: 'center'
              }}
            ></div>
          </div>
          <div className='w-full my-6 flex justify-between items-end'>
            <h2 className='text-2xl sm:text-4xl font-medium text-gray-900 text-center mt-4'>
              Nuestro Staff
            </h2>
            <span className='w-24 flex items-center justify-center hover:justify-between'>
              <Link href={'/nosotros'}>
                <a className='mr-1'>Ver todos</a>
              </Link>
              <BsArrowRight />
            </span>
          </div>
          <div className='w-full h-auto grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 '>
            {members.slice(2, 7).map(({ _id, firstName, lastName, role, image }) => (
              <MemberCard
                key={_id}
                role={role}
                firstName={firstName}
                lastName={lastName}
                image={image}
              />
            ))}
          </div>
          <div className='w-full my-6 flex justify-between items-end'>
            <h2 className='text-2xl sm:text-4xl font-medium text-gray-900 text-center mt-4'>
              Testimonios
            </h2>
            <span className='w-24 flex items-center justify-center hover:justify-between'>
              <Link href={'/testimonios'}>
                <a className='mr-1'>Ver todos</a>
              </Link>
              <BsArrowRight />
            </span>
          </div>
          <div className='w-full h-auto grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 xl:grid-cols-5 gap-4'>
            {testimonials.slice(5, 10).map(({ _id, firstName, lastName, image, content }) => (
              <TestimonialCard
                key={_id}
                firstName={firstName}
                lastName={lastName}
                image={image}
                content={content}
              />
            ))}
          </div>
          <div className='w-full my-6 flex justify-between items-end'>
            <h2 className='text-2xl sm:text-4xl font-medium text-gray-900 text-center mt-4'>
              Ultimas Novedades
            </h2>
            <span className='w-24 flex items-center justify-center hover:justify-between'>
              <Link href={'/novedades'}>
                <a className='mr-1'>Ver todos</a>
              </Link>
              <BsArrowRight />
            </span>
          </div>
          <div className='w-full h-auto grid grid-cols-1 sm:grid-cols-2 gap-4'>
            {news.slice(0, 2).map(({ _id, name, image, content }) => (
              <NewCard key={_id} id={_id} name={name} image={image} content={content} />
            ))}
          </div>
        </div>
      </div>
    </>
  )
}

export async function getStaticProps() {
  const membersResponse = await fetch('http://localhost:3000/api/members', {
    method: 'GET',
    mode: 'cors',
    headers: { 'Content-Type': 'application/json' }
  })

  const testimonialsResponse = await fetch('http://localhost:3000/api/testimonials', {
    method: 'GET',
    mode: 'cors',
    headers: { 'Content-Type': 'application/json' }
  })

  const newsResponse = await fetch('http://localhost:3000/api/news', {
    method: 'GET',
    mode: 'cors',
    headers: { 'Content-Type': 'application/json' }
  })

  const { data: members } = await membersResponse.json()
  const { data: testimonials } = await testimonialsResponse.json()
  const { data: news } = await newsResponse.json()

  console.log(news)

  return {
    props: {
      members,
      testimonials,
      news
    }
  }
}
